name: whisqr_puncher
description: The Whisqr puncher application.
publish_to: "none"
version: 0.1.0+6

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^1.0.2
  flutter_secure_storage: ^4.1.0
  url_launcher: ^6.0.2
  overlay_support: ^1.2.0
  qr_code_scanner: ^0.4.0-nullsafety.0
  crypto: ^3.0.0
  mobx: ^2.0.0-nullsafety.6
  flutter_mobx: ^2.0.0-nullsafety.3
  provider: ^5.0.0
  collection: ^1.15.0-nullsafety.4
  flutter_text_helpers:
    git:
      url: https://github.com/zvikarp/flutter_text_helpers
  dio:
    git:
      url: https://github.com/zvikarp/dio
      path: dio

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  auto_route_generator: ^1.0.2
  mobx_codegen: ^2.0.0-nullsafety.2

flutter:
  assets:
    - assets/lang/

  fonts:
    - family: Neuton
      fonts:
        - asset: assets/fonts/Neuton/Neuton-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Neuton/Neuton-Light.ttf
          weight: 300
        - asset: assets/fonts/Neuton/Neuton-Regular.ttf
          weight: 400
        - asset: assets/fonts/Neuton/Neuton-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Neuton/Neuton-Bold.ttf
          weight: 700
        - asset: assets/fonts/Neuton/Neuton-ExtraBold.ttf
          weight: 800
  uses-material-design: true
